services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
      - APP_URL=http://localhost:8080
      - SESSION_DOMAIN=localhost
      - SESSION_DRIVER=file
      - SESSION_SECURE_COOKIE=false
    volumes:
      - ./:/var/www
      - vendor_data:/var/www/vendor
      - /var/www/node_modules
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    command: sh -c "
      mkdir -p /var/www/database &&
      touch /var/www/database/database.sqlite &&
      chmod 666 /var/www/database/database.sqlite &&
      chmod -R 777 storage bootstrap/cache &&
      php artisan config:clear &&
      php artisan cache:clear &&
      php artisan config:cache &&
      php artisan migrate --force &&
      php-fpm"
    networks:
      - laravel
  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel
  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: unless-stopped
    ports:
      - '6380:6379'
    networks:
      - laravel
networks:
  laravel:
    driver: bridge
volumes:
  vendor_data:
